# fly.toml file generated for lolsite on 2022-04-02T11:02:04-06:00

app = "lolsite"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[processes]
web = "gunicorn --bind :8000 --workers 2 lolsite.wsgi:application"
worker = "celery -A lolsite worker --loglevel=INFO"

[deploy]
  release_command = "sh /release.sh"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "TRUE"
  DJANGO_SETTINGS_MODULE = 'lolsite.settings_live'

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
