# fly.toml app configuration file generated for lolsite on 2023-05-26T10:29:48-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lolsite"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "sh /release.sh"

[env]
  DJANGO_SETTINGS_MODULE = "lolsite.settings_live"
  PORT = "8000"
  PYTHONUNBUFFERED = "TRUE"

[processes]
  beat = "celery -A lolsite beat -l INFO"
  web = "gunicorn --bind :8000 --workers 12 lolsite.wsgi:application"
  worker = "celery -A lolsite worker --loglevel=INFO"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
