# Generated by Django 2.1.5 on 2019-02-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_gamemode_gametype_map_queue_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='name',
            new_name='_map',
        ),
    ]
