# Generated by Django 2.1.5 on 2019-02-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190206_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReforgedRune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(db_index=True)),
                ('icon', models.CharField(blank=True, default='', max_length=256)),
                ('key', models.CharField(blank=True, default='', max_length=128)),
                ('long_description', models.CharField(blank=True, default='', max_length=2048)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('short_description', models.CharField(blank=True, default='', max_length=1024)),
                ('row', models.IntegerField()),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReforgedTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(db_index=True)),
                ('language', models.CharField(blank=True, db_index=True, default='en_US', max_length=32)),
                ('version', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('icon', models.CharField(blank=True, default='', max_length=128)),
                ('key', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reforgedtree',
            unique_together={('_id', 'language', 'version')},
        ),
        migrations.AddField(
            model_name='reforgedrune',
            name='reforgedtree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforgedrunes', to='data.ReforgedTree'),
        ),
        migrations.AlterUniqueTogether(
            name='reforgedrune',
            unique_together={('reforgedtree', '_id')},
        ),
    ]
