# Generated by Django 2.1.5 on 2019-02-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190207_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='depth',
            field=models.IntegerField(null=True),
        ),
    ]
