# Generated by Django 2.1.5 on 2019-02-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190207_0155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('_id', 'version', 'language')},
        ),
    ]
