# Generated by Django 2.1.5 on 2019-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190207_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(db_index=True)),
                ('version', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('full', models.CharField(blank=True, default='', max_length=128)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                ('h', models.IntegerField()),
                ('sprite', models.CharField(blank=True, default='', max_length=128)),
                ('w', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profileicon',
            unique_together={('_id', 'version', 'language')},
        ),
    ]
