# Generated by Django 2.1.5 on 2019-02-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190207_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(db_index=True)),
                ('version', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('key', models.IntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('partype', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(blank=True, default='', max_length=128)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                ('h', models.IntegerField()),
                ('sprite', models.CharField(blank=True, default='', max_length=128)),
                ('w', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='data.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='data.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.FloatField()),
                ('armor_per_level', models.FloatField()),
                ('attack_damage', models.FloatField()),
                ('attack_damage_per_level', models.FloatField()),
                ('attack_range', models.FloatField()),
                ('attack_speed', models.FloatField()),
                ('attack_speed_per_level', models.FloatField()),
                ('crit', models.FloatField()),
                ('crit_per_level', models.FloatField()),
                ('hp', models.FloatField()),
                ('hp_per_level', models.FloatField()),
                ('hp_regen', models.FloatField()),
                ('hp_regen_per_level', models.FloatField()),
                ('move_speed', models.FloatField()),
                ('mp', models.FloatField()),
                ('mp_per_level', models.FloatField()),
                ('mp_regen', models.FloatField()),
                ('mp_regen_per_level', models.FloatField()),
                ('spell_block', models.FloatField()),
                ('spell_block_per_level', models.FloatField()),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='data.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('champions', models.ManyToManyField(related_name='tags', to='data.Champion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='champion',
            unique_together={('_id', 'version', 'language')},
        ),
    ]
