# Generated by Django 2.1.5 on 2019-02-07 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190207_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
