# Generated by Django 2.1.5 on 2019-02-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_champion_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionEffectBurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_int', models.IntegerField()),
                ('value', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionPassive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionPassiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(blank=True, default='', max_length=128)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                ('h', models.IntegerField()),
                ('sprite', models.CharField(blank=True, default='', max_length=128)),
                ('w', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('passive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='data.ChampionPassive')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('chromas', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('cooldown_burn', models.CharField(blank=True, default='', max_length=128)),
                ('cost_burn', models.CharField(blank=True, default='', max_length=128)),
                ('cost_type', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('max_ammo', models.CharField(blank=True, default='', max_length=128)),
                ('max_rank', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('range_burn', models.CharField(blank=True, default='', max_length=128)),
                ('resource', models.CharField(blank=True, default='', max_length=128)),
                ('tooltip', models.CharField(blank=True, default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(blank=True, default='', max_length=256)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                ('h', models.IntegerField()),
                ('sprite', models.CharField(blank=True, default='', max_length=128)),
                ('w', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='data.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff', models.FloatField()),
                ('key', models.CharField(blank=True, default='', max_length=32)),
                ('link', models.CharField(blank=True, default='', max_length=128)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='data.ChampionSpell')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='lore',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='championspell',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='data.Champion'),
        ),
        migrations.AddField(
            model_name='championskin',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='data.Champion'),
        ),
        migrations.AddField(
            model_name='championpassive',
            name='champion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passive', to='data.Champion'),
        ),
        migrations.AddField(
            model_name='championeffectburn',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_burn', to='data.ChampionSpell'),
        ),
        migrations.AlterUniqueTogether(
            name='championspellvar',
            unique_together={('spell', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='championspell',
            unique_together={('champion', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='championeffectburn',
            unique_together={('spell', 'sort_int')},
        ),
    ]
