# Generated by Django 2.1.5 on 2019-02-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190208_0135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championskin',
            unique_together={('champion', '_id')},
        ),
    ]
