# Generated by Django 2.1.5 on 2019-02-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20190208_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='championspellvar',
            name='sort_int',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='championspellvar',
            unique_together={('spell', 'sort_int')},
        ),
    ]
