# Generated by Django 2.1.5 on 2019-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190208_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championspellvar',
            name='coeff',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
