# Generated by Django 2.1.5 on 2019-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190208_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerspelleffectburn',
            name='value',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
