# Generated by Django 2.1.5 on 2019-03-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20190211_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstats',
            name='attack_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='attack_speed_per_level',
            field=models.FloatField(null=True),
        ),
    ]
