# Generated by Django 2.2.2 on 2019-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20190305_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='major',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='minor',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='patch',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
