# Generated by Django 2.2.2 on 2019-08-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20190613_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
