# Generated by Django 2.2.2 on 2020-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20190805_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='rito',
            name='last_data_import',
            field=models.DateTimeField(null=True),
        ),
    ]
