# Generated by Django 2.2.2 on 2020-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_rito_last_data_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='last_changed',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='rito',
            name='versions',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
    ]
