# Generated by Django 2.2.2 on 2020-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20200614_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_changed',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
