# Generated by Django 3.0.7 on 2020-07-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_item_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileicon',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profileicon',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profileicon',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
