# Generated by Django 3.0.7 on 2020-07-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200722_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='reforgedtree',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reforgedtree',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reforgedtree',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
