# Generated by Django 3.0.7 on 2021-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200722_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerspell',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summonerspell',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summonerspell',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
