# Generated by Django 3.1.6 on 2021-03-26 20:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20210326_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.save_location),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='file_15',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.save_location),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='file_30',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.save_location),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='file_40',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.save_location),
        ),
    ]
