# Generated by Django 4.1.6 on 2023-02-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20210326_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='patch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='patch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileicon',
            name='patch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reforgedtree',
            name='patch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='patch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
