# Generated by Django 4.2.2 on 2023-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_champion_patch_alter_item_patch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileicon',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reforgedtree',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
