# Generated by Django 4.2.2 on 2023-07-22 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_champion_minor_alter_item_minor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDSummonerSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('minor', models.IntegerField(blank=True, default=None, null=True)),
                ('patch', models.IntegerField(blank=True, default=None, null=True)),
                ('ext_id', models.BigIntegerField()),
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('summoner_level', models.IntegerField()),
                ('cooldown', models.IntegerField()),
                ('game_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None)),
                ('icon_path', models.CharField(default='', max_length=256)),
            ],
            options={
                'unique_together': {('ext_id', 'major', 'minor')},
            },
        ),
    ]
