# Generated by Django 4.2.3 on 2023-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_cdsummonerspell'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDProfileIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('minor', models.IntegerField(blank=True, default=None, null=True)),
                ('patch', models.IntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ext_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('year_released', models.IntegerField()),
                ('is_legacy', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
