# Generated by Django 4.2.3 on 2023-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_cdprofileicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='plaintext',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
