# Generated by Django 4.2.7 on 2024-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_add_diff_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percent_crit_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
