# Generated by Django 4.2.7 on 2024-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_item_percent_crit_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flat_magic_penetration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
