# Generated by Django 5.1.2 on 2024-10-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_item_flat_magic_penetration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
