# Generated by Django 5.1.2 on 2024-11-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_delete_season'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameMode',
        ),
        migrations.DeleteModel(
            name='GameType',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
