# Generated by Django 6.0.4 on 2026-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_delete_gamemode_delete_gametype_delete_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='adaptive_force',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
