# Generated by Django 6.0.4 on 2026-08-30 18:27

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_item_adaptive_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdprofileicon',
            name='image_url',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('https://raw.communitydragon.org/'), django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('major', models.CharField()), models.Value('None')), models.Value('.'), django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('minor', models.CharField()), models.Value('None')), models.Value('/plugins/rcp-be-lol-game-data/global/default/v1/profile-icons/'), 'ext_id', models.Value('.jpg')), output_field=models.CharField(max_length=256)),
        ),
    ]
