# Generated by Django 5.1.2 on 2024-11-02 19:42

import django.contrib.postgres.fields
import stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerchampion',
            name='version',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=stats.models.ArrayConstructor(models.F('major'), models.F('minor')), output_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
        ),
    ]
