# Generated by Django 5.1.2 on 2024-11-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_summonerchampion_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dmpm',
        ),
    ]
