# Generated by Django 5.1.2 on 2024-11-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_summonerchampion_dmpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dmpm',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dpm',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dtopm',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dtpm',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='dttpm',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='kda',
        ),
        migrations.RemoveField(
            model_name='summonerchampion',
            name='vspm',
        ),
    ]
