# Generated by Django 2.1.5 on 2019-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, db_index=True, default='', max_length=128, unique=True)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=8)),
                ('account_id', models.CharField(blank=True, db_index=True, default='', max_length=128, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('profile_icon_id', models.IntegerField(default=0)),
                ('puuid', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('revision_date', models.BigIntegerField(db_index=True, default=0)),
                ('summoner_level', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('region', 'name')},
        ),
    ]
