# Generated by Django 2.1.5 on 2019-02-06 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
