# Generated by Django 2.1.5 on 2019-02-06 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_summoner_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(default='', max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Summoner')),
            ],
        ),
    ]
