# Generated by Django 2.1.5 on 2019-02-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_namechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namechange',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namechanges', to='player.Summoner'),
        ),
    ]
