# Generated by Django 2.1.5 on 2019-02-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190206_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='simple_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
