# Generated by Django 2.1.5 on 2019-02-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_summoner_simple_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='last_summoner_page_import',
            field=models.DateTimeField(null=True),
        ),
    ]
