# Generated by Django 2.1.5 on 2019-03-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_summoner_last_summoner_page_import'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('region', 'account_id', '_id')},
        ),
    ]
