# Generated by Django 2.1.5 on 2019-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20190302_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='puuid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
