# Generated by Django 2.1.5 on 2019-03-07 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20190302_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankcheckpoints', to='player.Summoner')),
            ],
        ),
        migrations.CreateModel(
            name='RankPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_blood', models.BooleanField(blank=True, default=False)),
                ('hot_streak', models.BooleanField(blank=True, default=False)),
                ('inactive', models.BooleanField(blank=True, default=False)),
                ('veteran', models.BooleanField(blank=True, default=False)),
                ('league_points', models.IntegerField(blank=True, default=0, null=True)),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('losses', models.IntegerField(blank=True, default=0)),
                ('series_progress', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('position', models.CharField(blank=True, default='NONE', max_length=32, null=True)),
                ('queue_type', models.CharField(blank=True, default='', max_length=32)),
                ('rank', models.CharField(blank=True, default='', max_length=32)),
                ('tier', models.CharField(blank=True, default='', max_length=32)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='player.RankCheckpoint')),
            ],
        ),
    ]
