# Generated by Django 2.2.2 on 2019-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_summoner_full_import_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='ranked_import_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
