# Generated by Django 2.2.2 on 2019-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_summoner_ranked_import_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankposition',
            name='rank_integer',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
