# Generated by Django 2.2.2 on 2019-08-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0016_rankposition_rank_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, max_length=128)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('summoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Summoner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
