# Generated by Django 2.2.2 on 2019-09-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_summonerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='revision_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_level',
            field=models.IntegerField(default=0),
        ),
    ]
