# Generated by Django 2.2.2 on 2019-09-26 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0019_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Favorite',
        ),
    ]
