# Generated by Django 2.2.2 on 2019-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_auto_20190926_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
