# Generated by Django 2.2.2 on 2019-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_auto_20191120_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerlink',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
