# Generated by Django 2.2.2 on 2019-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_auto_20191126_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerlink',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
