# Generated by Django 3.0.7 on 2020-07-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_auto_20200626_1706'),
        ('player', '0028_auto_20200702_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='match.Match'),
        ),
    ]
