# Generated by Django 3.0.7 on 2020-07-02 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0029_auto_20200702_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
