# Generated by Django 3.0.7 on 2020-07-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0030_auto_20200702_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
