# Generated by Django 3.0.7 on 2020-07-13 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0032_auto_20200710_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerlink',
            name='summoner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summonerlinks', to='player.Summoner'),
        ),
        migrations.AlterField(
            model_name='summonerlink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summonerlinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
