# Generated by Django 3.0.7 on 2020-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_auto_20200712_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerlink',
            name='profile_icon_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
