# Generated by Django 3.0.7 on 2020-10-07 16:19
from django.db import migrations


# create gin index on simple_name
forward_simple_name = """
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE INDEX player_summoner_simple_name_trgm ON player_summoner USING gin(simple_name gin_trgm_ops);
"""
reverse_simple_name = """
    DROP INDEX player_summoner_simple_name_trgm;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0034_summonerlink_profile_icon_id'),
    ]

    operations = [
        migrations.RunSQL(sql=forward_simple_name, reverse_sql=reverse_simple_name),
    ]
