# Generated by Django 3.2.7 on 2021-09-26 19:50

from django.db import migrations


def set_null(apps, schema):
    Summoner = apps.get_model('player', 'Summoner')
    Summoner.objects.filter(puuid='').delete()
    Summoner.objects.filter(puuid=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_custom_default_summoner'),
    ]

    operations = [
        migrations.RunPython(set_null, migrations.RunPython.noop),
    ]
