# Generated by Django 3.2.7 on 2021-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0037_auto_20210926_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='puuid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
