# Generated by Django 4.1.2 on 2023-01-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0039_reputation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together=set(),
        ),
    ]
