# Generated by Django 4.1.6 on 2023-06-12 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0040_alter_summoner_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.summoner')),
            ],
        ),
    ]
