# Generated by Django 4.2.2 on 2023-06-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0041_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='simple_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
