# Generated by Django 4.2.2 on 2023-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0042_alter_summoner_name_alter_summoner_simple_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
