# Generated by Django 4.2.3 on 2023-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0044_add_blank_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summoner",
            name="_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
    ]
