# Generated by Django 4.2.7 on 2023-11-05 23:30

from django.db import migrations, models


forward_simple_name = """
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE INDEX player_summoner_simple_riot_id_trgm ON player_summoner USING gin(simple_riot_id gin_trgm_ops);
"""
reverse_simple_name = """
    DROP INDEX player_summoner_simple_riot_id_trgm;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0046_summoner_riot_id_name_summoner_riot_id_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='simple_riot_id',
            field=models.CharField(default='', max_length=41),
        ),
        migrations.RunSQL(sql=forward_simple_name, reverse_sql=reverse_simple_name),
    ]
