# Generated by Django 4.2.7 on 2023-11-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0047_add_simple_riot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='simple_riot_id',
            field=models.CharField(db_index=True, default='', max_length=41),
        ),
    ]
