# Generated by Django 4.2.7 on 2024-02-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0048_alter_summoner_simple_riot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='riot_id_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
