# Generated by Django 5.1.1 on 2024-09-30 15:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0050_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='simple_riot_id',
        ),
        migrations.AddField(
            model_name='summoner',
            name='simple_riot_id',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(django.db.models.functions.text.Concat(models.F('riot_id_name'), models.Value('#'), models.F('riot_id_tagline'))), models.Value(' '), models.Value('')), output_field=models.CharField()),
        ),
    ]
