# Generated by Django 5.1.1 on 2024-10-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0050_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='huge_match_import_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
