# Generated by Django 5.1.1 on 2024-10-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0051_alter_summoner_simple_riot_id'),
        ('player', '0051_summoner_huge_match_import_at'),
    ]

    operations = [
    ]
