# Generated by Django 5.1.2 on 2024-10-18 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0052_merge_20241005_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='region',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='simple_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
