# Generated by Django 5.1.2 on 2025-06-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0053_alter_summoner__id_alter_summoner_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='account_id',
        ),
    ]
