# Generated by Django 5.1.2 on 2025-06-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0054_remove_summoner_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='_id',
        ),
    ]
