# Generated by Django 5.2.5 on 2026-02-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0056_summonernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
