# Generated by Django 5.2.5 on 2026-02-16 02:09

from django.db import migrations, models


def backfill_riot_id_from_name(apps, schema_editor):
    Summoner = apps.get_model("player", "Summoner")
    Summoner.objects.filter(
        riot_id_name="",
    ).exclude(
        name="",
    ).update(
        riot_id_name=models.F("name"),
        riot_id_tagline="old",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0057_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_riot_id_from_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='summoner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='simple_name',
        ),
    ]
