export const buildings_default = {
    'BLUE-TOWER_BUILDING-BOT_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 10504,
        y: 1029,
    },
    'RED-TOWER_BUILDING-BOT_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 13866,
        y: 4505,
    },
    'BLUE-TOWER_BUILDING-MID_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 5846,
        y: 6396,
    },
    'RED-TOWER_BUILDING-MID_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 8955,
        y: 8510,
    },
    'BLUE-TOWER_BUILDING-TOP_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 981,
        y: 10441,
    },
    'RED-TOWER_BUILDING-TOP_LANE-OUTER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 4318,
        y: 13875,
    },

    'BLUE-TOWER_BUILDING-BOT_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 7000,
        y: 1700,
    },
    'RED-TOWER_BUILDING-BOT_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 13327,
        y: 8226,
    },
    'BLUE-TOWER_BUILDING-MID_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 5048,
        y: 4812,
    },
    'RED-TOWER_BUILDING-MID_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 9767,
        y: 10113,
    },
    'BLUE-TOWER_BUILDING-TOP_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 1512,
        y: 6699,
    },
    'RED-TOWER_BUILDING-TOP_LANE-INNER_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 7943,
        y: 13411,
    },

    'BLUE-TOWER_BUILDING-BOT_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 4000,
        y: 1400,
    },
    'RED-TOWER_BUILDING-BOT_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 13624,
        y: 10572,
    },
    'BLUE-TOWER_BUILDING-MID_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 3651,
        y: 3696,
    },
    'RED-TOWER_BUILDING-MID_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 11134,
        y: 11207,
    },
    'BLUE-TOWER_BUILDING-TOP_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 1112,
        y: 4800,
    },
    'RED-TOWER_BUILDING-TOP_LANE-BASE_TURRET': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 10481,
        y: 13650,
    },

    'BLUE-TOWER_BUILDING-MID_LANE-NEXUS_TURRET-top': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 1500,
        y: 2300,
    },
    'RED-TOWER_BUILDING-MID_LANE-NEXUS_TURRET-top': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 12611,
        y: 13084,
    },
    'BLUE-TOWER_BUILDING-MID_LANE-NEXUS_TURRET-bot': {
        type: 'tower',
        team: 'blue',
        is_alive: true,
        x: 2177,
        y: 1807,
    },
    'RED-TOWER_BUILDING-MID_LANE-NEXUS_TURRET-bot': {
        type: 'tower',
        team: 'red',
        is_alive: true,
        x: 13052,
        y: 12612,
    },

    'BLUE-INHIBITOR_BUILDING-BOT_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'blue',
        is_alive: true,
        x: 3300,
        y: 1400,
    },
    'RED-INHIBITOR_BUILDING-BOT_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'red',
        is_alive: true,
        x: 13624,
        y: 11372,
    },
    'BLUE-INHIBITOR_BUILDING-MID_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'blue',
        is_alive: true,
        x: 3203,
        y: 3208,
    },
    'RED-INHIBITOR_BUILDING-MID_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'red',
        is_alive: true,
        x: 11598,
        y: 11667,
    },
    'BLUE-INHIBITOR_BUILDING-TOP_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'blue',
        is_alive: true,
        x: 1000,
        y: 3900,
    },
    'RED-INHIBITOR_BUILDING-TOP_LANE-UNDEFINED_TURRET': {
        type: 'inhib',
        team: 'red',
        is_alive: true,
        x: 11261,
        y: 13676,
    },
}

