# Generated by Django 2.1.5 on 2019-02-14 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=1024)),
                ('hidden_message', models.CharField(blank=True, default='', max_length=256)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
