# Generated by Django 2.1.5 on 2019-02-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalmessage',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
