# Generated by Django 2.1.5 on 2019-02-05 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField()),
                ('pick_turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.BigIntegerField()),
                ('game_creation', models.BigIntegerField()),
                ('game_duration', models.IntegerField()),
                ('game_mode', models.CharField(blank=True, default='', max_length=32)),
                ('game_type', models.CharField(blank=True, default='', max_length=32)),
                ('map_id', models.IntegerField()),
                ('platform_id', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('queue_id', models.IntegerField(db_index=True)),
                ('season_id', models.IntegerField(db_index=True)),
                ('game_version', models.CharField(blank=True, default='', max_length=32)),
                ('major', models.IntegerField(db_index=True)),
                ('minor', models.IntegerField(db_index=True)),
                ('patch', models.IntegerField()),
                ('build', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('account_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('current_account_id', models.CharField(blank=True, default='', max_length=128)),
                ('current_platform_id', models.CharField(blank=True, default='', max_length=16)),
                ('match_history_uri', models.CharField(blank=True, default='', max_length=128)),
                ('summoner_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('summoner_name', models.CharField(blank=True, default='', max_length=256)),
                ('champion_id', models.IntegerField()),
                ('highest_achieved_season_tier', models.CharField(blank=True, default='', max_length=64)),
                ('spell_1_id', models.IntegerField()),
                ('spell_2_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('lane', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=128)),
                ('value_type', models.CharField(blank=True, choices=[('bool', 'bool'), ('int', 'int')], default='int', max_length=16)),
                ('value_bool', models.BooleanField(blank=True, default=False)),
                ('value_int', models.BigIntegerField(blank=True, default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='match.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('baron_kills', models.IntegerField(blank=True, default=0)),
                ('dominion_victory_score', models.IntegerField(blank=True, default=0)),
                ('dragon_kills', models.IntegerField(blank=True, default=0)),
                ('first_baron', models.BooleanField(blank=True, default=False)),
                ('first_blood', models.BooleanField(blank=True, default=False)),
                ('first_dragon', models.BooleanField(blank=True, default=False)),
                ('first_inhibitor', models.BooleanField(blank=True, default=False)),
                ('first_rift_herald', models.BooleanField(blank=True, default=False)),
                ('first_tower', models.BooleanField(blank=True, default=False)),
                ('inhibitor_kills', models.IntegerField(blank=True, default=0)),
                ('rift_herald_kills', models.IntegerField(blank=True, default=0)),
                ('tower_kills', models.IntegerField(blank=True, default=0)),
                ('vilemaw_kills', models.IntegerField(blank=True, default=0)),
                ('win', models.BooleanField(blank=True, default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=256)),
                ('value', models.FloatField(blank=True, default=0)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='match.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='ban',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='match.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('participant', 'key', 'start')},
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('participant', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('match', '_id')},
        ),
    ]
