# Generated by Django 2.1.5 on 2019-02-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='platform_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
