# Generated by Django 2.1.5 on 2019-02-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_participant_platform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
