# Generated by Django 2.1.5 on 2019-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20190206_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='win_str',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
