# Generated by Django 2.1.5 on 2019-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_team_win_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='summoner_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, null=True),
        ),
    ]
