# Generated by Django 2.1.5 on 2019-03-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20190216_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_interval', models.IntegerField(blank=True, default=60000)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='AssistingParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(blank=True, default='', max_length=128)),
                ('participant_id', models.IntegerField(blank=True, default=0)),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('level_up_type', models.CharField(blank=True, max_length=128, null=True)),
                ('skill_slot', models.IntegerField(blank=True, null=True)),
                ('ward_type', models.CharField(blank=True, max_length=128, null=True)),
                ('before_id', models.IntegerField(blank=True, null=True)),
                ('after_id', models.IntegerField(blank=True, null=True)),
                ('killer_id', models.IntegerField(blank=True, null=True)),
                ('victim_id', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('monster_type', models.CharField(blank=True, max_length=128, null=True)),
                ('monster_sub_type', models.CharField(blank=True, max_length=128, null=True)),
                ('building_type', models.CharField(blank=True, max_length=128, null=True)),
                ('lane_type', models.CharField(blank=True, max_length=32, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('tower_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_int', models.IntegerField(blank=True, db_index=True, default=0)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='match.AdvancedTimeline')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(blank=True, default=0)),
                ('current_gold', models.IntegerField(blank=True, default=0)),
                ('dominion_score', models.IntegerField(blank=True, default=0)),
                ('jungle_minions_killed', models.IntegerField(blank=True, default=0)),
                ('level', models.IntegerField(blank=True, default=1)),
                ('minions_killed', models.IntegerField(blank=True, default=0)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantframes', to='match.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, default=0)),
                ('y', models.IntegerField(blank=True, default=0)),
                ('team_score', models.IntegerField(blank=True, default=0)),
                ('total_gold', models.IntegerField(blank=True, default=0)),
                ('xp', models.IntegerField(blank=True, default=0)),
                ('participantframe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.ParticipantFrame')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='match.Frame'),
        ),
        migrations.AddField(
            model_name='assistingparticipants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistingparticipants', to='match.Event'),
        ),
    ]
