# Generated by Django 2.1.5 on 2019-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20190304_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='sort_int',
        ),
        migrations.AddField(
            model_name='frame',
            name='timestamp',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
