# Generated by Django 2.1.5 on 2019-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20190304_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
