# Generated by Django 2.1.5 on 2019-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20190304_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantframe',
            name='dominion_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
