# Generated by Django 2.2.2 on 2019-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20190312_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='summoner_name_simplified',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
