# Generated by Django 2.2.2 on 2019-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_participant_summoner_name_simplified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_creation',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
