# Generated by Django 2.2.2 on 2019-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20190919_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='platform_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='match',
            name='season_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='summoner_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='win_str',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
