# Generated by Django 2.2.2 on 2019-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_auto_20191120_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='champion_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
