# Generated by Django 2.2.2 on 2019-11-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_auto_20191120_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
