# Generated by Django 2.2.2 on 2019-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_auto_20191121_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='summoner_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, null=True),
        ),
    ]
