# Generated by Django 2.2.2 on 2019-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0018_auto_20191121_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='current_account_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='current_platform_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
