# Generated by Django 2.2.2 on 2020-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0020_auto_20200311_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='participant',
            name='tier',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
