# Generated by Django 2.2.2 on 2020-06-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_auto_20200604_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tier',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
