# Generated by Django 2.2.2 on 2020-06-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0022_auto_20200604_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role_label',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
