# Generated by Django 2.2.2 on 2020-06-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0024_livematch_livematchplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livematchplayer',
            name='match',
        ),
        migrations.DeleteModel(
            name='LiveMatch',
        ),
        migrations.DeleteModel(
            name='LiveMatchPlayer',
        ),
    ]
