# Generated by Django 3.0.7 on 2021-02-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_auto_20200626_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='major',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='minor',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='patch',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
