# Generated by Django 3.2.7 on 2021-09-26 09:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0027_match_is_fully_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('assisting_participant_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None)),
                ('building_type', models.CharField(max_length=32)),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('lane_type', models.CharField(max_length=32)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('team_id', models.PositiveSmallIntegerField()),
                ('tower_type', models.CharField(max_length=32, null=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChampionKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('bounty', models.PositiveSmallIntegerField()),
                ('kill_streak_length', models.PositiveSmallIntegerField()),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('victim_id', models.PositiveSmallIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChampionSpecialKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('assisting_participant_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None)),
                ('kill_type', models.CharField(max_length=32)),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('multi_kill_length', models.PositiveSmallIntegerField(default=None, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EliteMonsterKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('assisting_participant_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
                ('killer_team_id', models.PositiveSmallIntegerField()),
                ('monster_type', models.CharField(max_length=64)),
                ('monster_sub_type', models.CharField(max_length=64, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameEndEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('game_id', models.PositiveBigIntegerField()),
                ('real_timestamp', models.PositiveBigIntegerField()),
                ('winning_team', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDestroyedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('item_id', models.PositiveSmallIntegerField()),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPurchasedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('item_id', models.PositiveSmallIntegerField()),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemUndoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('before_id', models.PositiveSmallIntegerField()),
                ('after_id', models.PositiveSmallIntegerField()),
                ('gold_gain', models.SmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelUpEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('level', models.PositiveSmallIntegerField()),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLevelUpEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('level_up_type', models.CharField(max_length=32)),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('skill_slot', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurretPlateDestroyedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('lane_type', models.CharField(max_length=16)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('team_id', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VictimDamageDealt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('magic_damage', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('physical_damage', models.PositiveSmallIntegerField()),
                ('spell_name', models.CharField(max_length=64)),
                ('spell_slot', models.SmallIntegerField()),
                ('true_damage', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('championkillevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.championkillevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VictimDamageReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('magic_damage', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('physical_damage', models.PositiveSmallIntegerField()),
                ('spell_name', models.CharField(max_length=64)),
                ('spell_slot', models.SmallIntegerField()),
                ('true_damage', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('championkillevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.championkillevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WardKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('killer_id', models.PositiveSmallIntegerField()),
                ('ward_type', models.CharField(max_length=32)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WardPlacedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('creator_id', models.PositiveSmallIntegerField()),
                ('ward_type', models.CharField(max_length=32)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='frame',
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='participant',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='spell_1_id',
            new_name='summoner_1_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='spell_2_id',
            new_name='summoner_2_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='current_account_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='current_platform_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='highest_achieved_season_tier',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='match_history_uri',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='platform_id',
        ),
        migrations.RemoveField(
            model_name='participantframe',
            name='dominion_score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='combat_player_score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='objective_player_score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_0',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_1',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_3',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_4',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_5',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_6',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_7',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_8',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player_score_9',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='total_player_score',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='total_score_rank',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_str',
        ),
        migrations.AddField(
            model_name='participant',
            name='champ_experience',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='individual_position',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='puuid',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner_1_casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner_2_casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_position',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='ability_haste',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='ability_power',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='armor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='armor_pen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='armor_pen_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='attack_damage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='attack_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='bonus_armor_pen_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='bonus_magic_pen_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='cc_reduction',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='cooldown_reduction',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='gold_per_second',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='health',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='health_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='health_regen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='lifesteal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_damage_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_damage_done_to_champions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_damage_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_pen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_pen_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='magic_resist',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='movement_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='omnivamp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='physical_damage_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='physical_damage_done_to_champions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='physical_damage_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='physical_vamp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='power',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='power_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='power_regen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='spell_vamp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='time_enemy_spent_controlled',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='total_damage_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='total_damage_done_to_champions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='total_damage_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='true_damage_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='true_damage_done_to_champions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='participantframe',
            name='true_damage_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='detector_wards_placed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='spell_1_casts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='spell_2_casts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='spell_3_casts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='spell_4_casts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='total_damage_shielded_on_teammates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='total_heals_on_teammates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AssistingParticipants',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
