# Generated by Django 3.2.7 on 2021-09-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0028_v5_match_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSoldEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('item_id', models.PositiveSmallIntegerField()),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.frame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
