# Generated by Django 3.2.7 on 2021-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0029_itemsoldevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimdamagedealt',
            name='magic_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagedealt',
            name='physical_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagedealt',
            name='spell_slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagedealt',
            name='true_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagereceived',
            name='magic_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagereceived',
            name='physical_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagereceived',
            name='spell_slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='victimdamagereceived',
            name='true_damage',
            field=models.IntegerField(),
        ),
    ]
