# Generated by Django 3.2.7 on 2021-10-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0030_auto_20210929_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.BigIntegerField(),
        ),
    ]
