# Generated by Django 4.1.2 on 2022-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0033_elitemonsterkillevent_bounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='first_inhibitor_assist',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='first_inhibitor_kill',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='neutral_minions_killed_enemy_jungle',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='neutral_minions_killed_team_jungle',
        ),
        migrations.AddField(
            model_name='stats',
            name='all_in_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='assist_me_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='bait_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='basic_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='command_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='danger_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='enemy_missing_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='enemy_vision_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='game_ended_in_early_surrender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='game_ended_in_surrender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='get_back_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='hold_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='need_vision_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='on_my_way_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='push_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='riot_id_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='stats',
            name='riot_id_tagline',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='stats',
            name='vision_cleared_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
