# Generated by Django 4.1.2 on 2023-01-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0035_alter_match_is_fully_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='champion_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='summoner_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='summoner_name_simplified',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
