# Generated by Django 4.1.6 on 2023-06-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0037_alter_match_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='total_ally_jungle_minions_killed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='total_enemy_jungle_minions_killed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
