# Generated by Django 4.2.2 on 2023-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0039_alter_frame_timestamp_alter_participant__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='minor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
