# Generated by Django 4.2.2 on 2023-07-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0040_alter_match_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdestroyedevent',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempurchasedevent',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemundoevent',
            name='after_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemundoevent',
            name='before_id',
            field=models.PositiveIntegerField(),
        ),
    ]
