# Generated by Django 4.2.2 on 2023-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0041_alter_itemdestroyedevent_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='subteam_placement',
            field=models.IntegerField(default=0),
        ),
    ]
