# Generated by Django 4.2.7 on 2023-11-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0044_matchsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsummary",
            name="status",
            field=models.CharField(
                choices=[("r", "Retrieving"), ("c", "Complete"), ("f", "Failed")],
                default="r",
                max_length=1,
            ),
        ),
    ]
