# Generated by Django 5.1.1 on 2024-10-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0048_match_end_of_game_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='riot_id_name',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='riot_id_tagline',
        ),
    ]
