# Generated by Django 5.1.2 on 2024-11-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0051_alter_ban_unique_together_alter_team_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='detector_wards_placed',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='killing_sprees',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='largest_critical_strike',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='largest_killing_spree',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='longest_time_spent_living',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='sight_wards_bought_in_game',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='turret_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='unreal_kills',
        ),
    ]
