# Generated by Django 5.1.2 on 2025-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0052_remove_stats_detector_wards_placed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsoldevent',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
    ]
