# Generated by Django 5.1.2 on 2025-06-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0053_alter_itemsoldevent_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='summoner_id',
        ),
    ]
