# Generated by Django 5.2.5 on 2025-11-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0054_remove_participant_summoner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='damage_dealt_to_epic_monsters',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
