# Generated by Django 5.2.5 on 2026-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0055_stats_damage_dealt_to_epic_monsters'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role_bound_item',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
