# Generated by Django 5.2.5 on 2026-02-16 02:09

from django.db import migrations, models


def backfill_riot_id_from_summoner_name(apps, schema_editor):
    Participant = apps.get_model("match", "Participant")
    Participant.objects.filter(
        riot_id_name="",
    ).exclude(
        summoner_name="",
    ).update(
        riot_id_name=models.F("summoner_name"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0056_participant_role_bound_item'),
    ]

    operations = [
        migrations.RunPython(backfill_riot_id_from_summoner_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='participant',
            name='summoner_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='summoner_name_simplified',
        ),
    ]
