# Generated by Django 6.0.4 on 2026-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0057_remove_participant_summoner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_creation',
            field=models.BigIntegerField(),
        ),
    ]
