# Generated by Django 6.0.4 on 2026-08-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0058_alter_match_game_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ('timestamp',)},
        ),
    ]
