# Generated by Django 6.0.4 on 2026-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0059_alter_frame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championkillevent',
            name='shutdown_bounty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
