# Generated by Django 2.1.5 on 2019-02-22 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('state', models.CharField(default='', max_length=128)),
                ('group_position', models.IntegerField(default=0)),
                ('best_of', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BreakpointInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BreakpointStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, default=0)),
                ('closed', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(blank=True, db_index=True, default=0, unique=True)),
                ('slug', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('guid', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=16)),
                ('drupal_id', models.IntegerField(blank=True, default=0)),
                ('logo_url', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.CharField(blank=True, default='', max_length=100000)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='pro.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='pro.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('league_reference', models.CharField(blank=True, default='', max_length=256)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='pro.League')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('generated_name', models.CharField(blank=True, default='', max_length=128)),
                ('game_id', models.CharField(blank=True, default='', max_length=128)),
                ('game_realm', models.CharField(blank=True, default='', max_length=128)),
                ('platform_id', models.CharField(blank=True, default='', max_length=128)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pro.BracketMatch')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StandingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_int', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('group_position', models.IntegerField(blank=True, default=0)),
                ('group_name', models.CharField(blank=True, default='', max_length=128)),
                ('can_manufacture', models.BooleanField(blank=True, default=False)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='pro.LeagueTournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBreakpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='pro.LeagueTournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('team_reference', models.CharField(blank=True, default='', max_length=128)),
                ('team', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='pro.LeagueTournament')),
            ],
        ),
        migrations.AddField(
            model_name='standingresult',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standingresults', to='pro.TournamentRoster'),
        ),
        migrations.AddField(
            model_name='standingresult',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pro.BreakpointStandings'),
        ),
        migrations.AddField(
            model_name='matchinput',
            name='breakpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchinputs', to='pro.TournamentBreakpoint'),
        ),
        migrations.AddField(
            model_name='matchinput',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='pro.BracketMatch'),
        ),
        migrations.AddField(
            model_name='matchinput',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchinputs', to='pro.TournamentRoster'),
        ),
        migrations.AddField(
            model_name='gameinput',
            name='breakpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinputs', to='pro.TournamentBreakpoint'),
        ),
        migrations.AddField(
            model_name='gameinput',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pro.MatchGame'),
        ),
        migrations.AddField(
            model_name='gameinput',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinputs', to='pro.TournamentRoster'),
        ),
        migrations.AddField(
            model_name='breakpointstandings',
            name='breakpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='pro.TournamentBreakpoint'),
        ),
        migrations.AddField(
            model_name='breakpointinput',
            name='breakpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='pro.TournamentBreakpoint'),
        ),
        migrations.AddField(
            model_name='breakpointinput',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpointinputs', to='pro.TournamentRoster'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='pro.TournamentBracket'),
        ),
        migrations.AddField(
            model_name='bracketinput',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='pro.TournamentBracket'),
        ),
        migrations.AddField(
            model_name='bracketinput',
            name='breakpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracketinputs', to='pro.TournamentBreakpoint'),
        ),
        migrations.AddField(
            model_name='bracketinput',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracketinputs', to='pro.TournamentRoster'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentroster',
            unique_together={('tournament', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='standingresult',
            unique_together={('standing', 'sort_int')},
        ),
        migrations.AlterUniqueTogether(
            name='matchinput',
            unique_together={('match', 'roster')},
        ),
        migrations.AlterUniqueTogether(
            name='matchgame',
            unique_together={('match', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguetournament',
            unique_together={('league', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguename',
            unique_together={('league', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='leagueabout',
            unique_together={('league', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='gameinput',
            unique_together={('game', 'roster')},
        ),
        migrations.AlterUniqueTogether(
            name='breakpointinput',
            unique_together={('breakpoint', 'roster')},
        ),
        migrations.AlterUniqueTogether(
            name='bracketinput',
            unique_together={('bracket', 'roster', 'breakpoint', 'standing')},
        ),
    ]
