# Generated by Django 2.1.5 on 2019-02-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20190216_0200'),
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='match_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.Match'),
        ),
    ]
