# Generated by Django 2.1.5 on 2019-02-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_matchgame_match_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_hash', models.CharField(blank=True, default='', max_length=128)),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('hometown', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('live_game_team', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('photo_url', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('role_slug', models.CharField(blank=True, default='', max_length=128)),
                ('slug', models.CharField(blank=True, default='', max_length=128)),
                ('is_starter', models.BooleanField(default=False)),
                ('is_sub', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pro.MatchDetails')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.CharField(blank=True, default='', max_length=256)),
                ('scheduled_time', models.DateTimeField(db_index=True, null=True)),
                ('block_label', models.IntegerField(null=True)),
                ('block_prefix', models.CharField(blank=True, default='', max_length=128)),
                ('sub_block_label', models.IntegerField(null=True)),
                ('sub_block_prefix', models.CharField(blank=True, default='', max_length=128)),
                ('stage_label', models.CharField(blank=True, default='', max_length=128)),
                ('league_label', models.CharField(blank=True, default='', max_length=128)),
                ('tournament_label', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleitems', to='pro.MatchDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('slug', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('guid', models.CharField(blank=True, default='', max_length=128)),
                ('team_photo_url', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('logo_url', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('acronym', models.CharField(blank=True, default='', max_length=16)),
                ('home_league', models.CharField(blank=True, default='', max_length=128)),
                ('alt_logo_url', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pro.MatchDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=0)),
                ('slug', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('locale', models.CharField(blank=True, default='', max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pro.MatchDetails')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bracketmatch',
            unique_together={('bracket', '_id')},
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pro.Team'),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pro.BracketMatch'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='pro.MatchDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('details', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('details', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('details', '_id')},
        ),
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('details', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('details', '_id')},
        ),
    ]
