# Generated by Django 2.1.5 on 2019-02-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20190224_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetournament',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaguetournament',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
